### ISSUE TITLE
panic when launch ireader

### ISSUE THREAD

**Issue by cheyiliu** [cheyiliu/demo.1000.20150101#19]
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-1ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -53
D/StateMachine(  279): handleMessage: X

I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 21fd, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 21fd
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 21fd
I/PowerManagerService-JNI(  279): [Stability] PowerManagerService_userActivity JNI pass power key event to PowerManagerService userActivity()
W/CpuWake (  279): >>acquireCpuPerfWakeLock!
W/CpuWake (  279): <<acquireCpuPerfWakeLock!
I/ActivityManager(  279): START intent from pid 26176
I/Intent  (  279): @test_code: getHtcIntentFlag: 0 obj: 1097233928
D/SensorService(  279): disable: get sensor name = BMA250 3-axis Accelerometer
D/Sensors (  279): Enable G-Sensor: en = 0
D/Sensors (  279): mEnabled = 0x0
D/Sensors (  279): /data/misc/AccPrmsF.ini does not exist
D/SensorService(  279): SensorDevice::activate--: handle = 0x0, enabled = 0x0
D/SensorService(  279): pid=279, uid=1000
I/InputReader(  279): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  279): Device reconfigured: id=5, name='himax-touchscreen', surface size is now 480x800, mode is 1
D/PowerManagerService(  279): button light setOrientation:0
I/ActivityManager(  279): Config changed: {1.0 0mcc0mnc zh_CN layoutdir=0 sw320dp w320dp h508dp nrml long port finger -keyb/v/h -nav/h s.303 skin=default fontsize=3}
I/CVW     (  435): Dismiss CandidateViewWindow WCLID:0
W/View    (  435): The view is not attached to a window
D/BatteryService(  279): updateBatteryStats ======================================
D/ConnectivityService(  279): onUidRulesChanged(uid=10161, uidRules=0)
D/SST-GSM(0)(  454): received broadcast android.intent.action.CONFIGURATION_CHANGED
D/SST-GSM(1)(  454): received broadcast android.intent.action.CONFIGURATION_CHANGED
D/SST-GSM(0)(  454): Language is not changed, leave as what it was!!
D/SST-GSM(1)(  454): Language is not changed, leave as what it was!!
D/memalloc(26176): /dev/pmem: Unmapping buffer base:0x5679e000 size:18923520 offset:17387520
D/OpenGLRenderer(26176): Flushing caches (mode 0)
D/memalloc(26176): /dev/pmem: Unmapping buffer base:0x52f4b000 size:6144000 offset:4608000
D/memalloc(26176): /dev/pmem: Unmapping buffer base:0x54ede000 size:12165120 offset:10629120
D/memalloc(26176): /dev/pmem: Unmapping buffer base:0x52405000 size:1536000 offset:0
D/dalvikvm(26176): newInstance failed: no <init>()
D/AndroidRuntime(26176): Shutting down VM
W/dalvikvm(26176): threadid=1: thread exiting with uncaught exception (group=0x40a8b228)
I/wpa_supplicant(23851): wpa_drv_scan: wpa_s->driver->scan2 = 0x6391d
I/wpa_supplicant(23851): Scan requested (ret=0) - scan timeout 30 seconds
D/CarrierLabel(  347): CarrierLabel mIntentReceiver : android.intent.action.CONFIGURATION_CHANGED
E/AndroidRuntime(26176): FATAL EXCEPTION: main
E/AndroidRuntime(26176): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.foxluncher/com.foxluncher.ui.ActivityMain}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.foxluncher.ui.ActivityMain$FragmentPage: make sure class name exists, is public, and has an empty constructor that is public
E/AndroidRuntime(26176): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2205)
E/AndroidRuntime(26176): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2240)
E/AndroidRuntime(26176): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3809)
E/AndroidRuntime(26176): 	at android.app.ActivityThread.access$700(ActivityThread.java:139)
E/AndroidRuntime(26176): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime(26176): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26176): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(26176): 	at android.app.ActivityThread.main(ActivityThread.java:4987)
E/AndroidRuntime(26176): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26176): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(26176): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(26176): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(26176): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(26176): Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.foxluncher.ui.ActivityMain$FragmentPage: make sure class name exists, is public, and has an empty constructor that is public
E/AndroidRuntime(26176): 	at android.support.v4.app.Fragment.instantiate(Fragment.java:415)
E/AndroidRuntime(26176): 	at android.support.v4.app.FragmentState.instantiate(Fragment.java:99)
E/AndroidRuntime(26176): 	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1807)
E/AndroidRuntime(26176): 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:214)
E/AndroidRuntime(26176): 	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:98)
E/AndroidRuntime(26176): 	at com.foxluncher.ui.ActivityMain.onCreate(ActivityMain.java:69)
E/AndroidRuntime(26176): 	at android.app.Activity.performCreate(Activity.java:4538)
E/AndroidRuntime(26176): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
E/AndroidRuntime(26176): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2161)
E/AndroidRuntime(26176): 	... 12 more
E/AndroidRuntime(26176): Caused by: java.lang.InstantiationException: can't instantiate class com.foxluncher.ui.ActivityMain$FragmentPage; no empty constructor
E/AndroidRuntime(26176): 	at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime(26176): 	at java.lang.Class.newInstance(Class.java:1319)
E/AndroidRuntime(26176): 	at android.support.v4.app.Fragment.instantiate(Fragment.java:404)
E/AndroidRuntime(26176): 	... 20 more
E/EmbeddedLogger(  279): App crashed! Process: com.foxluncher
E/EmbeddedLogger(  279): App crashed! Package: com.foxluncher v1 (1.0)
E/EmbeddedLogger(  279): Application Label: FoxLuncher
D/ViewRootImpl(  279): @@@- disable SystemServer HW acceleration
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/wpa_supplicant(23851): nl80211: New scan results available
I/wpa_supplicant(23851): wlan0: [HTC] wpa_supplicant_event():2199- Got an original EVENT_SCAN_RESULTS
I/wpa_supplicant(23851): Got an original EVENT_SCAN_RESULTS
I/wpa_supplicant(23851):    selected BSS 28:2c:b2:ff:3b:26 ssid='chuangyan'
I/wpa_supplicant(23851): Considering within-ESS reassociation
I/wpa_supplicant(23851): Current BSS: 28:2c:b2:ff:3b:26 level=-53
I/wpa_supplicant(23851): Selected BSS: 28:2c:b2:ff:3b:26 level=-53
I/wpa_supplicant(23851): Skip roam - too small difference in signal level
D/StateMachine(  279): handleMessage: E msg.what=147461
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=147461 when=-1ms }
D/StateMachine(  279): processMsg: ConnectModeState
D/WifiStateMachine(  279): ConnectModeState{ what=147461 when=-1ms }
D/Tethering(  279): [isWifi] getHotspotEnabled: false
D/StateMachine(  279): processMsg: DriverStartedState
D/WifiStateMachine(  279): DriverStartedState{ what=147461 when=-6ms }
D/StateMachine(  279): processMsg: SupplicantStartedState
D/WifiStateMachine(  279): SupplicantStartedState{ what=147461 when=-6ms }
D/WirelessDisplayService(  279): Receive Wifi scan results available intent.
D/WirelessDisplayService(  279): HANDLE_WIFI_SCAN_RESULT_AVAILABLE, dongle scan = 0
D/WirelessDisplayService(  279): constructDongleInfoFromWifi() dongleScan = false
D/WirelessDisplayService(  279): Sending intent: MIRROR_DISPLAY_DONGLE_AVAILABLE_ACTION
D/WirelessDisplayService(  279): getDiscoveryDongleList
D/StateMachine(  279): handleMessage: X
D/dalvikvm(  347): GC_CONCURRENT freed 1998K, 54% free 6980K/15139K, paused 2ms+16ms
D/memalloc(  347): /dev/pmem: Unmapping buffer base:0x5400e000 size:9216000 offset:9011200
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/dalvikvm(26229): GC_FOR_ALLOC freed 764K, 21% free 3428K/4323K, paused 70ms
I/dalvikvm-heap(26229): Grow heap (frag case) to 4.894MB for 1536016-byte allocation
D/dalvikvm(26229): GC_FOR_ALLOC freed <1K, 16% free 4927K/5859K, paused 23ms
I/global  (26229): call socket shutdown
D/libEGL  (26229): loaded /system/lib/egl/libGLES_android.so
D/libEGL  (26229): loaded /system/lib/egl/libEGL_adreno200.so
D/libEGL  (26229): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
D/libEGL  (26229): loaded /system/lib/egl/libGLESv2_adreno200.so
I/Adreno200-EGLSUB(26229): <ConfigWindowMatch:1991>: Format RGBA_8888.
D/OpenGLRenderer(26229): Enabling debug mode 0
D/GSM(0)  (  454): getServiceState()
D/GSM(0)  (  454): getServiceState()
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/ActivityManager(  279): Displayed com.chaozh.iReaderFree/com.chaozh.iReader.ui.activity.WelcomeActivity: +998ms
D/WindowManager(  279): Starting rotation animaiton
D/WindowManager(  279): end of ratation animation
D/SqliteDatabaseCpp(26229): Registering sqlite logging func: /data/data/com.chaozh.iReaderFree/databases/iReader.db
D/SqliteDatabaseCpp(26229): DB info: open db, path = /data/data/com.chaozh.iReaderFree/databases , key = aVeYdev, flag = 6, file size = 22528
D/SqliteDatabaseCpp(26229): DB info: path = /data/data/com.chaozh.iReaderFree/databases , key = aVeYdev, handle: 0x1cf7330, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
D/SqliteDatabaseCpp(26229): DB info: open db, path = /data/data/com.chaozh.iReaderFree/databases , key = mYvoet, flag = 6, file size = 5120
D/SqliteDatabaseCpp(26229): DB info: path = /data/data/com.chaozh.iReaderFree/databases , key = mYvoet, handle: 0x1d608b8, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
D/SqliteDatabaseCpp(26229): DB info: open db, path = /data/data/com.chaozh.iReaderFree/databases , key = tYwo, flag = 6, file size = 6144
D/SqliteDatabaseCpp(26229): DB info: path = /data/data/com.chaozh.iReaderFree/databases , key = tYwo, handle: 0x1d79888, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
W/System.err(26229): java.io.FileNotFoundException: /iReader/cover/cover.xhtml: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:406)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
W/System.err(26229): 	at dg.d.b(SourceFile:457)
W/System.err(26229): 	at bz.d.c(SourceFile:165)
W/System.err(26229): 	at com.zhangyue.iReader.app.APP.n(SourceFile:642)
W/System.err(26229): 	at com.chaozh.iReader.ui.activity.i.run(SourceFile:355)
W/System.err(26229): 	at java.lang.Thread.run(Thread.java:864)
W/System.err(26229): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.Posix.open(Native Method)
W/System.err(26229): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:390)
W/System.err(26229): 	... 8 more
W/System.err(26229): java.io.FileNotFoundException: /iReader/cover/cover_1.png: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:406)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
W/System.err(26229): 	at dg.d.b(SourceFile:457)
W/System.err(26229): 	at bz.d.c(SourceFile:168)
W/System.err(26229): 	at com.zhangyue.iReader.app.APP.n(SourceFile:642)
W/System.err(26229): 	at com.chaozh.iReader.ui.activity.i.run(SourceFile:355)
W/System.err(26229): 	at java.lang.Thread.run(Thread.java:864)
W/System.err(26229): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.Posix.open(Native Method)
W/System.err(26229): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:390)
W/System.err(26229): 	... 8 more
W/System.err(26229): java.io.FileNotFoundException: /iReader/cover/cover_2.png: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:406)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
W/System.err(26229): 	at dg.d.b(SourceFile:457)
W/System.err(26229): 	at bz.d.c(SourceFile:171)
W/System.err(26229): 	at com.zhangyue.iReader.app.APP.n(SourceFile:642)
W/System.err(26229): 	at com.chaozh.iReader.ui.activity.i.run(SourceFile:355)
W/System.err(26229): 	at java.lang.Thread.run(Thread.java:864)
W/System.err(26229): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.Posix.open(Native Method)
W/System.err(26229): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:390)
W/System.err(26229): 	... 8 more
W/System.err(26229): java.io.FileNotFoundException: /iReader/cover/epub.xhtml: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:406)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:128)
W/System.err(26229): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:117)
W/System.err(26229): 	at dg.d.b(SourceFile:457)
W/System.err(26229): 	at bz.d.c(SourceFile:174)
W/System.err(26229): 	at com.zhangyue.iReader.app.APP.n(SourceFile:642)
W/System.err(26229): 	at com.chaozh.iReader.ui.activity.i.run(SourceFile:355)
W/System.err(26229): 	at java.lang.Thread.run(Thread.java:864)
W/System.err(26229): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(26229): 	at libcore.io.Posix.open(Native Method)
W/System.err(26229): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err(26229): 	at libcore.io.IoBridge.open(IoBridge.java:390)
W/System.err(26229): 	... 8 more
D/SqliteDatabaseCpp(26229): DB info: open db, path = /data/data/com.chaozh.iReaderFree/databases , key = TFBaleDksjl, flag = 6, file size = 6144
D/SqliteDatabaseCpp(26229): DB info: path = /data/data/com.chaozh.iReaderFree/databases , key = TFBaleDksjl, handle: 0x1de4620, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
D/GSM(0)  (  454): getServiceState()
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-1ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -56
D/StateMachine(  279): handleMessage: X
I/Intent  (  279): @test_code: getHtcIntentFlag: 0 obj: 1089108968
W/CpuWake (  279): >>acquireCpuPerfWakeLock!
W/CpuWake (  279): <<acquireCpuPerfWakeLock!
I/ActivityManager(  279): START intent from pid 26229
I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 21fe, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 21fe
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 21fe
D/dalvikvm(26229): GC_CONCURRENT freed 1416K, 23% free 5336K/6883K, paused 2ms+3ms
D/dalvikvm(26229): GC_FOR_ALLOC freed 260K, 24% free 5284K/6883K, paused 24ms
I/dalvikvm-heap(26229): Grow heap (frag case) to 6.077MB for 875536-byte allocation
D/dalvikvm(26229): GC_FOR_ALLOC freed 4K, 22% free 6135K/7779K, paused 22ms
D/dalvikvm(26229): GC_FOR_ALLOC freed 42K, 20% free 6250K/7779K, paused 23ms
I/dalvikvm-heap(26229): Grow heap (frag case) to 7.135MB for 996496-byte allocation
D/dalvikvm(26229): GC_FOR_ALLOC freed 5K, 19% free 7218K/8803K, paused 24ms
D/dalvikvm(26229): GC_FOR_ALLOC freed 0K, 19% free 7218K/8803K, paused 24ms
I/dalvikvm-heap(26229): Grow heap (frag case) to 7.666MB for 561616-byte allocation
D/dalvikvm(26229): GC_FOR_ALLOC freed 0K, 18% free 7766K/9379K, paused 26ms
D/dalvikvm(26229): Trying to load lib /data/data/com.chaozh.iReaderFree/files/com.maa.sdk/lib/libwsld.so 0x40e0dfb0
D/dalvikvm(26229): Added shared lib /data/data/com.chaozh.iReaderFree/files/com.maa.sdk/lib/libwsld.so 0x40e0dfb0
D/webview (26229): [InitTabEffectPivot] >> nScreenWidth = 480
D/webview (26229): [InitTabEffectPivot] >> nScreenHeight = 800
D/SqliteDatabaseCpp(26229): DB info: open db, path = /data/data/com.chaozh.iReaderFree/databases , key = sefraes, flag = 6, file size = 12288
D/dalvikvm(26229): GC_CONCURRENT freed 1973K, 22% free 7594K/9699K, paused 3ms+6ms
D/SqliteDatabaseCpp(26229): DB info: path = /data/data/com.chaozh.iReaderFree/databases , key = sefraes, handle: 0x1e2e838, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
D/dalvikvm(  279): GC_EXPLICIT freed 498K, 28% free 12705K/17571K, paused 5ms+16ms
I/PackageManager(  279):  setEnabledSetting(), pkgName=com.chaozh.iReaderFree, clsName=io.yunba.android.core.YunBaReceiver, state=1, flag=1, pid=26229, uid=10161
I/global  (26229): In close() at SocketHttpClientConnection
I/PowerManagerService-JNI(  279): [Stability] PowerManagerService_userActivity JNI pass power key event to PowerManagerService userActivity()
D/Process (26176): killProcess, pid=26176
D/Process (26176): dalvik.system.VMStack.getThreadStackTrace(Native Method)
D/memalloc(  279): /dev/pmem: Unmapping buffer base:0x5a3f0000 size:14274560 offset:13905920
D/memalloc(  279): /dev/pmem: Unmapping buffer base:0x58e62000 size:6512640 offset:6144000
D/Process (26176): java.lang.Thread.getStackTrace(Thread.java:599)
D/Process (26176): android.os.Process.killProcess(Process.java:807)
D/Process (26176): com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
D/Process (26176): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
D/Process (26176): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
D/Process (26176): dalvik.system.NativeStart.main(Native Method)
I/Process (26176): Sending signal. PID: 26176 SIG: 9
I/Adreno200-EGLSUB(26229): <ConfigWindowMatch:1991>: Format RGBA_8888.
I/ActivityManager(  279): Process com.foxluncher (pid 26176) has died.
W/ActivityManager(  279): Force removing ActivityRecord{412b21b8 com.foxluncher/.ui.ActivityMain}: app died, no saved state
D/ConnectivityService(  279): onUidRulesChanged(uid=10159, uidRules=0)
W/CpuWake (  279): >>releaseCpuPerfWakeLock
W/CpuWake (  279): <<releaseCpuPerfWakeLock
I/Adreno200-EGLSUB(26229): <ConfigWindowMatch:1991>: Format RGBA_8888.
D/dalvikvm(26229): GC_CONCURRENT freed 837K, 12% free 8577K/9699K, paused 2ms+5ms
W/InputManagerService(  279): Got RemoteException sending setActive(false) notification to pid 26176 uid 10159
I/InputManagerService(  279): [startInputLocked] Enable input method client.
D/PackageManager(  279): Failed to get PackageInfo!, pkg:com.google.android.youtube, flags:5
D/OpenGLRenderer(26229): has fontRender patch
D/dalvikvm(26229): Trying to load lib /data/data/com.chaozh.iReaderFree/lib/libUiControl.so 0x40e0dfb0
D/OpenGLRenderer(26229): has fontRender patch
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/dalvikvm(26229): Added shared lib /data/data/com.chaozh.iReaderFree/lib/libUiControl.so 0x40e0dfb0
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/ActivityManager(  279): Displayed com.chaozh.iReaderFree/com.zhangyue.iReader.bookshelf.ui.ActivityBookShelf: +2s759ms
D/SqliteDatabaseCpp(25528): DB info: open db, path = /data/data/com.tencent.android.qqdownloader/databases , key = feYgkj, flag = 6, file size = 413696
D/SqliteDatabaseCpp(25528): DB info: path = /data/data/com.tencent.android.qqdownloader/databases , key = feYgkj, handle: 0x1e3ed10, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
D/SqliteDatabaseCpp(25528): DB info: close db, path = /data/data/com.tencent.android.qqdownloader/databases , key = feYgkj, handle = 0x1e3ed10, type = w, r/w = (0, 0)
D/SqliteDatabaseCpp(25528): DB info: open db, path = /data/data/com.tencent.android.qqdownloader/databases , key = feYgkj, flag = 6, file size = 413696
D/SqliteDatabaseCpp(25528): DB info: path = /data/data/com.tencent.android.qqdownloader/databases , key = feYgkj, handle: 0x1e3ed10, type: w, r/w: (0,1), mode: truncate, disk free size: 448 M
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-3ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -52
D/StateMachine(  279): handleMessage: X
D/SqliteDatabaseCpp(25528): DB info: close db, path = /data/data/com.tencent.android.qqdownloader/databases , key = feYgkj, handle = 0x1e3ed10, type = w, r/w = (0, 0)
D/dalvikvm(26229): GC_FOR_ALLOC freed 1054K, 15% free 8903K/10467K, paused 34ms
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 21ff, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 21ff
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 21ff
D/OpenGLRenderer(26229): Flushing caches (mode 0)
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/memalloc(26229): /dev/pmem: Unmapping buffer base:0x534a8000 size:1536000 offset:0
D/memalloc(26229): /dev/pmem: Unmapping buffer base:0x53a1d000 size:6144000 offset:4608000
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
^C

**Comment by cheyiliu** [comment]
android:configChanges="orientation|keyboardHidden|screenSize"
