### ISSUE TITLE
panic when launch tudou

### ISSUE THREAD

**Issue by cheyiliu** [cheyiliu/demo.1000.20150101#20]
I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 23f4, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 23f4
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 23f4
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-3ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -55
D/StateMachine(  279): handleMessage: X
I/PowerManagerService-JNI(  279): [Stability] PowerManagerService_userActivity JNI pass power key event to PowerManagerService userActivity()
W/CpuWake (  279): >>acquireCpuPerfWakeLock!
W/CpuWake (  279): <<acquireCpuPerfWakeLock!
I/ActivityManager(  279): START intent from pid 27531
I/Intent  (  279): @test_code: getHtcIntentFlag: 0 obj: 1092139944
I/ActivityManager(  279): Start proc com.tudou.android for activity com.tudou.android/com.tudou.ui.activity.WelcomeActivity: pid=27572 uid=10162 gids={3003, 1006, 1015, 1007}
D/SensorService(  279): disable: get sensor name = BMA250 3-axis Accelerometer
D/Sensors (  279): Enable G-Sensor: en = 0
D/Sensors (  279): mEnabled = 0x0
D/Sensors (  279): /data/misc/AccPrmsF.ini does not exist
D/SensorService(  279): SensorDevice::activate--: handle = 0x0, enabled = 0x0
D/SensorService(  279): pid=279, uid=1000
I/InputReader(  279): Reconfiguring input devices.  changes=0x00000004
I/InputReader(  279): Device reconfigured: id=5, name='himax-touchscreen', surface size is now 480x800, mode is 1
D/PowerManagerService(  279): button light setOrientation:0
I/ActivityManager(  279): Config changed: {1.0 0mcc0mnc zh_CN layoutdir=0 sw320dp w320dp h508dp nrml long port finger -keyb/v/h -nav/h s.309 skin=default fontsize=3}
I/CVW     (  435): Dismiss CandidateViewWindow WCLID:0
W/View    (  435): The view is not attached to a window
D/OpenGLRenderer(27531): Flushing caches (mode 0)
D/ConnectivityService(  279): onUidRulesChanged(uid=10162, uidRules=0)
D/memalloc(27531): /dev/pmem: Unmapping buffer base:0x53008000 size:6144000 offset:4608000
D/SST-GSM(0)(  454): received broadcast android.intent.action.CONFIGURATION_CHANGED
D/SST-GSM(1)(  454): received broadcast android.intent.action.CONFIGURATION_CHANGED
D/SST-GSM(0)(  454): Language is not changed, leave as what it was!!
D/SST-GSM(1)(  454): Language is not changed, leave as what it was!!
D/memalloc(27531): /dev/pmem: Unmapping buffer base:0x53807000 size:12165120 offset:10629120
D/memalloc(27531): /dev/pmem: Unmapping buffer base:0x545be000 size:7680000 offset:6144000
D/dalvikvm(27531): newInstance failed: no <init>()
D/AndroidRuntime(27531): Shutting down VM
W/dalvikvm(27531): threadid=1: thread exiting with uncaught exception (group=0x40a8b228)
E/AndroidRuntime(27531): FATAL EXCEPTION: main
E/AndroidRuntime(27531): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.foxluncher/com.foxluncher.ui.ActivityMain}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.foxluncher.ui.ActivityMain$FragmentPage: make sure class name exists, is public, and has an empty constructor that is public
E/AndroidRuntime(27531): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2205)
E/AndroidRuntime(27531): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2240)
E/AndroidRuntime(27531): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3809)
E/AndroidRuntime(27531): 	at android.app.ActivityThread.access$700(ActivityThread.java:139)
E/AndroidRuntime(27531): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
E/AndroidRuntime(27531): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27531): 	at android.os.Looper.loop(Looper.java:156)
E/AndroidRuntime(27531): 	at android.app.ActivityThread.main(ActivityThread.java:4987)
E/AndroidRuntime(27531): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(27531): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(27531): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime(27531): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime(27531): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(27531): Caused by: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.foxluncher.ui.ActivityMain$FragmentPage: make sure class name exists, is public, and has an empty constructor that is public
E/AndroidRuntime(27531): 	at android.support.v4.app.Fragment.instantiate(Fragment.java:415)
E/AndroidRuntime(27531): 	at android.support.v4.app.FragmentState.instantiate(Fragment.java:99)
E/AndroidRuntime(27531): 	at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1807)
E/AndroidRuntime(27531): 	at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:214)
E/AndroidRuntime(27531): 	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:98)
E/AndroidRuntime(27531): 	at com.foxluncher.ui.ActivityMain.onCreate(ActivityMain.java:69)
E/AndroidRuntime(27531): 	at android.app.Activity.performCreate(Activity.java:4538)
E/AndroidRuntime(27531): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
E/AndroidRuntime(27531): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2161)
E/AndroidRuntime(27531): 	... 12 more
E/AndroidRuntime(27531): Caused by: java.lang.InstantiationException: can't instantiate class com.foxluncher.ui.ActivityMain$FragmentPage; no empty constructor
E/AndroidRuntime(27531): 	at java.lang.Class.newInstanceImpl(Native Method)
E/AndroidRuntime(27531): 	at java.lang.Class.newInstance(Class.java:1319)
E/AndroidRuntime(27531): 	at android.support.v4.app.Fragment.instantiate(Fragment.java:404)
E/AndroidRuntime(27531): 	... 20 more
E/EmbeddedLogger(  279): App crashed! Process: com.foxluncher
E/EmbeddedLogger(  279): App crashed! Package: com.foxluncher v1 (1.0)
E/EmbeddedLogger(  279): Application Label: FoxLuncher
D/ViewRootImpl(  279): @@@- disable SystemServer HW acceleration
D/CarrierLabel(  347): CarrierLabel mIntentReceiver : android.intent.action.CONFIGURATION_CHANGED
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/dalvikvm(  347): GC_CONCURRENT freed 2072K, 46% free 8289K/15139K, paused 2ms+25ms
D/memalloc(  347): /dev/pmem: Unmapping buffer base:0x548d9000 size:9216000 offset:9011200
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -55, Link speed: 24, Frequency: 2437, Net ID: 5, Explicit connect: false
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -55, Link speed: 24, Frequency: 2437, Net ID: 5, Explicit connect: false
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -55, Link speed: 24, Frequency: 2437, Net ID: 5, Explicit connect: false
D/SqliteDatabaseCpp(27572): Registering sqlite logging func: /data/data/com.tudou.android/databases/_ire
D/SqliteDatabaseCpp(27572): DB info: open db, path = /data/data/com.tudou.android/databases , key = [, flag = 6, file size = 5120
D/SqliteDatabaseCpp(27572): DB info: path = /data/data/com.tudou.android/databases , key = [, handle: 0x1cfed10, type: w, r/w: (0,1), mode: truncate, disk free size: 384 M
D/dalvikvm(27572): Trying to load lib /data/data/com.tudou.android/lib/libmresearch.so 0x40d60e30
D/dalvikvm(27572): Added shared lib /data/data/com.tudou.android/lib/libmresearch.so 0x40d60e30
D/dalvikvm(27572): No JNI_OnLoad found in /data/data/com.tudou.android/lib/libmresearch.so 0x40d60e30, skipping init
D/dalvikvm(27572): GC_CONCURRENT freed 1153K, 27% free 3469K/4707K, paused 2ms+3ms
D/SqliteDatabaseCpp(27572): DB info: open db, path = /data/data/com.tudou.android/databases , key = tudk, flag = 6, file size = 24576
D/SqliteDatabaseCpp(27572): DB info: path = /data/data/com.tudou.android/databases , key = tudk, handle: 0x1794e80, type: w, r/w: (0,1), mode: truncate, disk free size: 384 M
W/System  (27572): Ignoring HTTP header field 'User-Agent' because its value is null
D/SqliteDatabaseCpp(27572): DB info: close db, path = /data/data/com.tudou.android/databases , key = tudk, handle = 0x1794e80, type = w, r/w = (0, 0)
D/SqliteDatabaseCpp(27572): DB info: open db, path = /data/data/com.tudou.android/databases , key = tudk, flag = 6, file size = 24576
D/SqliteDatabaseCpp(27572): DB info: path = /data/data/com.tudou.android/databases , key = tudk, handle: 0x1794e80, type: w, r/w: (0,1), mode: truncate, disk free size: 384 M
D/SqliteDatabaseCpp(27572): DB info: close db, path = /data/data/com.tudou.android/databases , key = tudk, handle = 0x1794e80, type = w, r/w = (0, 0)
W/ImageLoader(27572): diskCache() and diskCacheFileNameGenerator() calls overlap each other
W/ApplicationContext(27572): Unable to create external files directory
D/SqliteDatabaseCpp(27572): DB info: open db, path = /data/data/com.tudou.android/databases , key = tudk, flag = 6, file size = 24576
D/SqliteDatabaseCpp(27572): DB info: path = /data/data/com.tudou.android/databases , key = tudk, handle: 0x1794e80, type: w, r/w: (0,1), mode: truncate, disk free size: 384 M
D/SqliteDatabaseCpp(27572): DB info: close db, path = /data/data/com.tudou.android/databases , key = tudk, handle = 0x1794e80, type = w, r/w = (0, 0)
D/SqliteDatabaseCpp(27572): DB info: open db, path = /data/data/com.tudou.android/databases , key = tudk, flag = 6, file size = 24576
D/SqliteDatabaseCpp(27572): DB info: path = /data/data/com.tudou.android/databases , key = tudk, handle: 0x1794e80, type: w, r/w: (0,1), mode: truncate, disk free size: 384 M
D/Socket_Alarm(27572): registerHTCSocketMonitorCallBack
D/Socket_Alarm(27572): set mSocketMonitor
D/Socket_Alarm(27572): HTCSocketMonitorImpl::HTCSocketMonitorImpl
I/dalvikvm(27572): Could not find method android.view.View.setBackground, referenced from method com.tudou.ui.activity.WelcomeActivity.setPosterImage
W/dalvikvm(27572): VFY: unable to resolve virtual method 6686: Landroid/view/View;.setBackground (Landroid/graphics/drawable/Drawable;)V
D/dalvikvm(27572): VFY: replacing opcode 0x6e at 0x0016
I/System.out(27572): ##openudid:4e9ca7518ca999be
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -55, Link speed: 24, Frequency: 2437, Net ID: 5, Explicit connect: false
W/Settings(27572): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
D/SqliteDatabaseCpp(27572): DB info: close db, path = /data/data/com.tudou.android/databases , key = tudk, handle = 0x1794e80, type = w, r/w = (0, 0)
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
V/LocationManagerService(  279): getProviders
W/System.err(27572): java.lang.IllegalArgumentException: provider==null
W/System.err(27572): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:441)
W/System.err(27572): 	at cn.com.mma.mobile.tracking.api.DeviceInfo.getLocation(Countly.java:950)
W/System.err(27572): 	at cn.com.mma.mobile.tracking.api.Countly.setTrackLocation(Countly.java:188)
W/System.err(27572): 	at com.tudou.ui.activity.WelcomeActivity.onCreate(WelcomeActivity.java:333)
W/System.err(27572): 	at android.app.Activity.performCreate(Activity.java:4538)
W/System.err(27572): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1071)
W/System.err(27572): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2161)
W/System.err(27572): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2240)
W/System.err(27572): 	at android.app.ActivityThread.access$600(ActivityThread.java:139)
W/System.err(27572): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1262)
W/System.err(27572): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(27572): 	at android.os.Looper.loop(Looper.java:156)
W/System.err(27572): 	at android.app.ActivityThread.main(ActivityThread.java:4987)
W/System.err(27572): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(27572): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(27572): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
W/System.err(27572): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
W/System.err(27572): 	at dalvik.system.NativeStart.main(Native Method)
D/SqliteDatabaseCpp(27572): DB info: open db, path = /data/data/com.tudou.android/databases , key = cYme[gej, flag = 6, file size = 5120
D/SqliteDatabaseCpp(27572): DB info: path = /data/data/com.tudou.android/databases , key = cYme[gej, handle: 0x1cfb6f8, type: w, r/w: (0,1), mode: truncate, disk free size: 384 M
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/dalvikvm(27572): GC_FOR_ALLOC freed 1183K, 26% free 3727K/5027K, paused 35ms
I/dalvikvm-heap(27572): Grow heap (frag case) to 7.627MB for 4096016-byte allocation
D/dalvikvm(27572): GC_FOR_ALLOC freed 24K, 15% free 7703K/9059K, paused 21ms
D/dalvikvm(27572): GC_FOR_ALLOC freed 199K, 15% free 7735K/9059K, paused 21ms
I/dalvikvm-heap(27572): Grow heap (frag case) to 10.783MB for 3300496-byte allocation
D/dalvikvm(27572): GC_FOR_ALLOC freed <1K, 12% free 10958K/12323K, paused 21ms
I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 23f5, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 23f5
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 23f5
D/PhoneStatusBarPolicy(  347): onSignalStrengthsChangedExt phoneType = 1
D/PhoneStatusBarPolicy(  347): onSignalStrengthsChangedExt SignalStrength: 25 -1 -1 -1 -1 -1 -1 99 -32767 -32767 -32767 -32767 gsm|lte
D/Bluetooth HS/HF(  454): HandsfreeMessageHandler 14
D/PhoneStatusBarPolicy(  347): updateSignalStrength mSimState=ABSENT mServiceState=1 home null null null  Unknown:0 CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1EriInd= -1EriMode= -1RadioPowerSv: falseEmergOnly: false PhoneType: 1 voiceRadioTechnology Unknown:0
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-4ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -59
D/StateMachine(  279): handleMessage: X
D/dalvikvm(27572): GC_FOR_ALLOC freed 3308K, 36% free 8459K/13155K, paused 21ms
I/dalvikvm-heap(27572): Grow heap (frag case) to 10.485MB for 2246416-byte allocation
W/CpuWake (  279): >>releaseCpuPerfWakeLock
W/CpuWake (  279): <<releaseCpuPerfWakeLock
D/dalvikvm(27572): GC_FOR_ALLOC freed <1K, 20% free 10653K/13155K, paused 24ms
D/dalvikvm(27572): GC_FOR_ALLOC freed 2507K, 32% free 9187K/13347K, paused 21ms
I/dalvikvm-heap(27572): Grow heap (frag case) to 13.502MB for 4665616-byte allocation
D/dalvikvm(27572): GC_FOR_ALLOC freed <1K, 24% free 13743K/17955K, paused 21ms
D/OpenUDID(27572): OpenUDID: 4e9ca7518ca999be
V/LocationManagerService(  279): getLastKnownLocation: gps
V/LocationManagerService(  279): getLastKnownLocation: network
V/LocationManagerService(  279): getLastKnownLocation: gps
V/LocationManagerService(  279): getLastKnownLocation: network
D/libEGL  (27572): loaded /system/lib/egl/libGLES_android.so
D/libEGL  (27572): loaded /system/lib/egl/libEGL_adreno200.so
D/libEGL  (27572): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
D/libEGL  (27572): loaded /system/lib/egl/libGLESv2_adreno200.so
I/Adreno200-EGLSUB(27572): <ConfigWindowMatch:1991>: Format RGBA_8888.
D/OpenGLRenderer(27572): Enabling debug mode 0
D/OpenGLRenderer(  367): Flushing caches (mode 1)
D/memalloc(  347): /dev/pmem: Unmapping buffer base:0x5236e000 size:204800 offset:0
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/ActivityManager(  279): Displayed com.tudou.android/com.tudou.ui.activity.WelcomeActivity: +2s852ms
D/WindowManager(  279): Starting rotation animaiton
D/WindowManager(  279): end of ratation animation
D/memalloc(  347): /dev/pmem: Unmapping buffer base:0x5400e000 size:9011200 offset:7680000
I/ActivityManager(  279): Process com.htc.task (pid 27298) has died.
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/OpenGLRenderer(  367): Flushing caches (mode 1)
D/OpenGLRenderer(  367): Flushing caches (mode 1)
D/OpenGLRenderer(  367): Flushing caches (mode 1)
D/dalvikvm(27572): GC_CONCURRENT freed 6176K, 38% free 11161K/17955K, paused 2ms+3ms
E/ImageLoader(27572): null
E/ImageLoader(27572): java.lang.NullPointerException
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.utils.ImageSizeUtils.computeImageSampleSize(ImageSizeUtils.java:99)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.prepareDecodingOptions(BaseImageDecoder.java:160)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:77)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
E/ImageLoader(27572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/ImageLoader(27572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/ImageLoader(27572): 	at java.lang.Thread.run(Thread.java:864)
E/ImageLoader(27572): null
E/ImageLoader(27572): java.lang.NullPointerException
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.utils.ImageSizeUtils.computeImageSampleSize(ImageSizeUtils.java:99)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.prepareDecodingOptions(BaseImageDecoder.java:160)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.decode.BaseImageDecoder.decode(BaseImageDecoder.java:77)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.decodeImage(LoadAndDisplayImageTask.java:264)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.tryLoadBitmap(LoadAndDisplayImageTask.java:222)
E/ImageLoader(27572): 	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask.run(LoadAndDisplayImageTask.java:135)
E/ImageLoader(27572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/ImageLoader(27572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/ImageLoader(27572): 	at java.lang.Thread.run(Thread.java:864)
W/CpuWake (  279): >>acquireCpuPerfWakeLock!
W/CpuWake (  279): <<acquireCpuPerfWakeLock!
I/ActivityManager(  279): START intent from pid 27572
I/Intent  (  279): @test_code: getHtcIntentFlag: 0 obj: 1095242888
V/LocationManagerService(  279): getLastKnownLocation: gps
V/LocationManagerService(  279): getLastKnownLocation: network
I/PowerManagerService-JNI(  279): [Stability] PowerManagerService_userActivity JNI pass power key event to PowerManagerService userActivity()
I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 23f6, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 23f6
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 23f6
D/Process (27531): killProcess, pid=27531
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-3ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -56
D/StateMachine(  279): handleMessage: X
D/memalloc(  279): /dev/pmem: Unmapping buffer base:0x57189000 size:573440 offset:204800
D/memalloc(  279): /dev/pmem: Unmapping buffer base:0x58e62000 size:1064960 offset:696320
D/Process (27531): dalvik.system.VMStack.getThreadStackTrace(Native Method)
D/Process (27531): java.lang.Thread.getStackTrace(Thread.java:599)
D/Process (27531): android.os.Process.killProcess(Process.java:807)
D/Process (27531): com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:104)
D/Process (27531): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
D/Process (27531): java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
D/Process (27531): dalvik.system.NativeStart.main(Native Method)
I/Process (27531): Sending signal. PID: 27531 SIG: 9
D/dalvikvm(27572): GC_CONCURRENT freed 2843K, 39% free 11102K/17955K, paused 2ms+3ms
I/ActivityManager(  279): Process com.foxluncher (pid 27531) has died.
W/ActivityManager(  279): Force removing ActivityRecord{40d81020 com.foxluncher/.ui.ActivityMain}: app died, no saved state
D/ConnectivityService(  279): onUidRulesChanged(uid=10159, uidRules=0)
D/dalvikvm(  279): GC_EXPLICIT freed 735K, 31% free 12974K/18659K, paused 6ms+15ms
I/ActivityManager(  279): Start proc com.tudou.android:SoUpgradeService for service com.tudou.android/com.youku.libmanager.SoUpgradeService: pid=27642 uid=10162 gids={3003, 1006, 1015, 1007}
D/dalvikvm(  104): GC_EXPLICIT freed 37K, 27% free 2809K/3807K, paused 2ms+2ms
D/dalvikvm(  104): GC_EXPLICIT freed <1K, 27% free 2809K/3807K, paused 3ms+2ms
D/dalvikvm(  104): GC_EXPLICIT freed <1K, 27% free 2809K/3807K, paused 2ms+3ms
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -56, Link speed: 11, Frequency: 2437, Net ID: 5, Explicit connect: false
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -56, Link speed: 11, Frequency: 2437, Net ID: 5, Explicit connect: false
D/Youku   (27572): null
D/WifiStateMachine(  279): syncRequestConnectionInfo mWifiInfo=SSID: chuangyan, BSSID: 28:2c:b2:ff:3b:26, MAC: a0:f4:50:c7:7b:af, Supplicant state: COMPLETED, RSSI: -56, Link speed: 11, Frequency: 2437, Net ID: 5, Explicit connect: false
V/LocationManagerService(  279): getLastKnownLocation: gps
V/LocationManagerService(  279): getLastKnownLocation: network
W/System.err(27572): java.lang.Exception
W/System.err(27572): 	at com.youku.network.HttpRequestManager.downloadUri(HttpRequestManager.java:163)
W/System.err(27572): 	at com.youku.network.HttpRequestManager.access$200(HttpRequestManager.java:48)
V/LocationManagerService(  279): getLastKnownLocation: gps
V/LocationManagerService(  279): getLastKnownLocation: network
W/System  (27572): Ignoring HTTP header field 'Cookie' because its value is null
W/System.err(27572): 	at com.youku.network.HttpRequestManager$1.doInBackground(HttpRequestManager.java:581)
W/ImageLoader(27642): diskCache() and diskCacheFileNameGenerator() calls overlap each other
W/ApplicationContext(27642): Unable to create external files directory
W/System.err(27572): 	at com.tudou.android.YoukuAsyncTask$2.call(YoukuAsyncTask.java:95)
W/System.err(27572): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
W/System.err(27572): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
W/System.err(27572): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
I/Adreno200-EGLSUB(27572): <ConfigWindowMatch:1991>: Format RGBA_8888.
W/System.err(27572): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
W/System.err(27572): 	at java.lang.Thread.run(Thread.java:864)
W/InputManagerService(  279): Got RemoteException sending setActive(false) notification to pid 27531 uid 10159
I/InputManagerService(  279): [startInputLocked] Enable input method client.
D/dalvikvm(27572): GC_CONCURRENT freed 2164K, 35% free 11706K/17955K, paused 2ms+18ms
D/dalvikvm(27642): GC_CONCURRENT freed 1160K, 27% free 3450K/4707K, paused 2ms+3ms
W/CpuWake (  279): >>releaseCpuPerfWakeLock
W/CpuWake (  279): <<releaseCpuPerfWakeLock
D/OpenGLRenderer(27572): has fontRender patch
D/OpenGLRenderer(27572): has fontRender patch
D/OpenGLRenderer(27572): has fontRender patch
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
I/ActivityManager(  279): Displayed com.tudou.android/com.tudou.ui.activity.HomePageActivity: +2s266ms
D/OpenGLRenderer(27572): Flushing caches (mode 0)
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/memalloc(27572): /dev/pmem: Unmapping buffer base:0x5349b000 size:6144000 offset:4608000
D/memalloc(27572): /dev/pmem: Unmapping buffer base:0x54dcc000 size:7680000 offset:6144000
D/dalvikvm(27572): GC_CONCURRENT freed 1782K, 29% free 12892K/17955K, paused 2ms+4ms
I/Adreno200-EGLSUB(  103): <CreateImage:813>: Android Image
I/Adreno200-EGLSUB(  103): <GetImageAttributes:1022>: RGBA_8888
D/dalvikvm(27572): GC_FOR_ALLOC freed 2177K, 24% free 13699K/17955K, paused 35ms
I/ONCRPC  (  102): rpc_handle_rpc_call: for Xid: 23f7, Prog: 31000000, Vers: fc37ad5c, Proc: 00000012
I/ONCRPC  (  102): rpc_handle_rpc_call: Find Status: 0 Xid: 23f7
I/ONCRPC  (  102): oncrpc_proxy_handle_cmd_rpc_call: Dispatching xid: 23f7
D/PhoneStatusBarPolicy(  347): onSignalStrengthsChangedExt phoneType = 1
D/PhoneStatusBarPolicy(  347): onSignalStrengthsChangedExt SignalStrength: 24 -1 -1 -1 -1 -1 -1 99 -32767 -32767 -32767 -32767 gsm|lte
D/Bluetooth HS/HF(  454): HandsfreeMessageHandler 14
D/PhoneStatusBarPolicy(  347): updateSignalStrength mSimState=ABSENT mServiceState=1 home null null null  Unknown:0 CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1EriInd= -1EriMode= -1RadioPowerSv: falseEmergOnly: false PhoneType: 1 voiceRadioTechnology Unknown:0
D/dalvikvm(27572): GC_FOR_ALLOC freed 570K, 19% free 14564K/17955K, paused 30ms
D/StateMachine(  279): handleMessage: E msg.what=131155
D/StateMachine(  279): processMsg: ConnectedState
D/WifiStateMachine(  279): ConnectedState{ what=131155 when=-4ms arg1=1 }
D/WifiStateMachine(  279): fetchRssiAndLinkSpeedNative RSSI = -53
D/StateMachine(  279): handleMessage: X
^C
housy@housy-desktop:~$

**Comment by cheyiliu** [comment]
android:configChanges="orientation|keyboardHidden|screenSize"

**Comment by cheyiliu** [comment]
http://stackoverflow.com/questions/12226652/onconfigurationchanged-problems
